### ISSUE TITLE
0.1.6 

### ISSUE THREAD

**Issue by durandom** [mdreizin/chrome-bookmarks-alfred-workflow#23]
Sorry, me again. 
Even after a clean install of 0.1.6 I get this:

```
Starting debug for 'Chrome Bookmarks'

[2017-02-08 19:15:50][ERROR: input.scriptfilter] Code 2: panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5bb4d]

goroutine 1 [running]:
panic(0x296c00, 0xc8200100b0)
	/home/travis/.gimme/versions/go1.6.2.linux.amd64/src/runtime/panic.go:481 +0x3e6
github.com/mdreizin/chrome-bookmarks-alfred-workflow/vendor/github.com/urfave/cli.HandleAction.func1(0xc8200c3618)
	/home/travis/gopath/src/github.com/mdreizin/chrome-bookmarks-alfred-workflow/vendor/github.com/urfave/cli/app.go:472 +0x417
panic(0x296c00, 0xc8200100b0)
	/home/travis/.gimme/versions/go1.6.2.linux.amd64/src/runtime/panic.go:443 +0x4e9
github.com/mdreizin/chrome-bookmarks-alfred-workflow/model.Browser.FullPathFor(0xc82000ed20, 0x24, 0xc820010e18, 0x6, 0xc8200149c0, 0x11, 0xc820010e50, 0xd, 0xc82000ed50, 0x2b, ...)
	/home/travis/gopath/src/github.com/mdreizin/chrome-bookmarks-alfred-workflow/model/browser.go:35 +0x1cd
github.com/mdreizin/chrome-bookmarks-alfred-workflow/repository.(*JsonProfileRepository).GetProfiles(0xc820011360, 0xc82000ed20, 0x24, 0xc820010e18, 0x6, 0xc8200149c0, 0x11, 0xc820010e50, 0xd, 0xc82000ed50, ...)
	/home/travis/gopath/src/github.com/mdreizin/chrome-bookmarks-alfred-workflow/repository/json_profile_repository.go:24 +0x138
github.com/mdreizin/chrome-bookmarks-alfred-workflow/service.(*DefaultBookmarkService).GetProfiles(0xc82000a840, 0xc82000ed20, 0x24, 0xc820010e18, 0x6, 0xc8200149c0, 0x11, 0xc820010e50, 0xd, 0xc82000ed50, ...)
	/home/travis/gopath/src/github.com/mdreizin/chrome-bookmarks-alfred-workflow/service/default_bookmark_service.go:48 +0x206
main.profileCommand.func1(0xc82008e280, 0x0, 0x0)
	/home/travis/gopath/src/github.com/mdreizin/chrome-bookmarks-alfred-workflow/cli/profile_command.go:20 +0x338
reflect.Value.call(0x237840, 0x35e238, 0x13, 0x2e55a0, 0x4, 0xc8200c3578, 0x1, 0x1, 0x0, 0x0, ...)
	/home/travis/.gimme/versions/go1.6.2.linux.amd64/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x237840, 0x35e238, 0x13, 0xc8200c3578, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.6.2.linux.amd64/src/reflect/value.go:303 +0xb1
github.com/mdreizin/chrome-bookmarks-alfred-workflow/vendor/github.com/urfave/cli.HandleAction(0x237840, 0x35e238, 0xc82008e280, 0x0, 0x0)
	/home/travis/gopath/src/github.com/mdreizin/chrome-bookmarks-alfred-workflow/vendor/github.com/urfave/cli/app.go:481 +0x2ee
github.com/mdreizin/chrome-bookmarks-alfred-workflow/vendor/github.com/urfave/cli.Command.Run(0x2f2030, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/mdreizin/chrome-bookmarks-alfred-workflow/vendor/github.com/urfave/cli/command.go:186 +0x1301
github.com/mdreizin/chrome-bookmarks-alfred-workflow/vendor/github.com/urfave/cli.(*App).Run(0xc820001080, 0xc82000a240, 0x4, 0x4, 0x0, 0x0)
	/home/travis/gopath/src/github.com/mdreizin/chrome-bookmarks-alfred-workflow/vendor/github.com/urfave/cli/app.go:235 +0xa9c
main.run(0x0, 0x0)
	/home/travis/gopath/src/github.com/mdreizin/chrome-bookmarks-alfred-workflow/cli/main.go:12 +0x55
main.main()
	/home/travis/gopath/src/github.com/mdreizin/chrome-bookmarks-alfred-workflow/cli/main.go:6 +0x18
```

**Comment by durandom** [comment]
thats the same for `chrome` and `chrome-profiles` keyword. Looks like you are shipping a  linux binary built on travis ?!

**Comment by s80275** [comment]
Me too. `chrome` & `chrome-profiles` got same debug result, not work.

**Comment by mdreizin** [comment]
@durandom @s80275 I have switched os from osx to linux and used cross-compilation. I have already tested it and I need some time to identify issue. I will post any updates soon.

**Comment by mdreizin** [comment]
@durandom @s80275 Could you please check out the latest RC version and and tell me does it work for you or not?

https://github.com/mdreizin/chrome-bookmarks-alfred-workflow/releases/tag/0.1.7-rc.4

**Comment by durandom** [comment]
Works now with Profile set to `Default`.
With Profile set to `Auto` it crashes with

```
Starting debug for 'Chrome Bookmarks'

[2017-02-09 09:55:59][input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?>
<items><item valid="true" arg="" uid=""><title>Auto (Active)</title><subtitle></subtitle><icon>img/chrome.png</icon></item><item valid="true" arg="Default" uid="Default"><title>Default</title><subtitle>~/Library/Application Support/Google/Chrome/Default</subtitle><icon>/Users/hild/Library/Application Support/Google/Chrome/Avatars/avatar_generic.png</icon></item></items>
[2017-02-09 09:56:03][input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?>
<items><item valid="false" arg="open /Users/hild/Library/Application Support/Google/Chrome/Bookmarks: no such file or directory" uid="error"><title>chrome-bookmarks</title><subtitle>Error: open /Users/hild/Library/Application Support/Google/Chrome/Bookmarks: no such file or directory</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>
[2017-02-09 09:56:03][input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?>
<items><item valid="false" arg="open /Users/hild/Library/Application Support/Google/Chrome/Bookmarks: no such file or directory" uid="error"><title>chrome-bookmarks</title><subtitle>Error: open /Users/hild/Library/Application Support/Google/Chrome/Bookmarks: no such file or directory</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>
[2017-02-09 09:56:03][input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?>
<items><item valid="false" arg="open /Users/hild/Library/Application Support/Google/Chrome/Bookmarks: no such file or directory" uid="error"><title>chrome-bookmarks</title><subtitle>Error: open /Users/hild/Library/Application Support/Google/Chrome/Bookmarks: no such file or directory</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>
```

**Comment by mdreizin** [comment]
@durandom I was surprised that:

```go
usr, _ := user.Current()
dir := usr.HomeDir
```

doesn't work correctly  in case of cross-compilation.

Just used:

```go
homeDir := os.Getenv("HOME")
```

**Comment by mdreizin** [comment]
@durandom @s80275 Now release is available https://github.com/mdreizin/chrome-bookmarks-alfred-workflow/releases/tag/0.1.7

**Comment by durandom** [comment]
Sorry, but I still got this with Profile set to `Auto`
Not a big issue for me, because Profile set to `Default` works

```
Starting debug for 'Chrome Bookmarks'

[2017-02-09 12:35:35][input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?>
<items><item valid="false" arg="open /Users/hild/Library/Application Support/Google/Chrome/Bookmarks: no such file or directory" uid="error"><title>chrome-bookmarks</title><subtitle>Error: open /Users/hild/Library/Application Support/Google/Chrome/Bookmarks: no such file or directory</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>
```

**Comment by mdreizin** [comment]
@durandom Thanks. I have just fixed that issue. Please check https://github.com/mdreizin/chrome-bookmarks-alfred-workflow/releases/tag/0.1.8-rc.1

**Comment by durandom** [comment]
ACK - works now. 
Thanks for fixing so fast...

**Comment by mdreizin** [comment]
@durandom @s80275 Please update to https://github.com/mdreizin/chrome-bookmarks-alfred-workflow/releases/tag/0.1.8
